---
title: "Oct-9-2024"
author: "Andrew Bazuro"
format: html
editor: visual
---

```{r}
rm(list = ls())
library(here)
library(tidyverse)
tomato <- read.csv(here("data", "tomato_data.csv"))
```

Write a line that returns the 3rd, 7th, and 9th rows of data.

```{r}
tomatoslim <- tomato |> slice(3, 7, 9)
```

Write a line of code that finds all of the plants from the fertilizer treatment with avg_tomato_weight_g > or equal to 145 g

```{r}
tomatosum <- tomato |> filter(Treatment == "Fertilizer") |> filter(Avg_tomato_weight_g >= 145)
```

```{r}
dir.create(here("Outputs"))

write.csv(tomato, here("Outputs", "tomatoes_fixed.csv"), row.names = FALSE) ##removes X1 row from dataset
toms2 <- read.csv(here("Outputs", "tomatoes_fixed.csv"))
```

```{r}
rm(list = ls())
lead <- read.csv(here("data", "NoCoLead.csv"))
summary(lead)
lead |> summarize(
  mean_num_tests = mean(num_tests)
) |> View()
```

What is the mean number of tests per year?

```{r}
lead |> 
  group_by(Year) |> 
  summarize(
    mean_tests_per_year = mean(num_tests)) |>
  View()
```

```{r}

```

